import { writeFileSync } from 'fs';
import { join } from 'path';
import { commitFiles } from '@/lib/git';
import type { ImpactReport, TaskSpec } from '@/types/index';

// ---------------------------------------------------------------------------
// TASK.md template
// ---------------------------------------------------------------------------

/**
 * Render a human-readable TASK.md from the task spec.
 * This is the file IBM Bob reads directly to understand the change request.
 */
function renderTaskMd(spec: TaskSpec): string {
  const affectedList = spec.affectedFiles.map((f) => `- \`${f}\``).join('\n');
  const criteriaList = spec.acceptanceCriteria.map((c) => `- ${c}`).join('\n');
  const commandList = spec.verificationCommands.map((c) => `\`\`\`\n${c}\n\`\`\``).join('\n\n');

  return `# RepoMind Task

> This file is managed by RepoMind and was last written by the verification
> layer. IBM Bob should read this file, implement the requested change, and
> commit the result so RepoMind can verify it.

---

## Change Request

${spec.changeRequest}

---

## Impact Analysis

**Risk Level:** ${spec.riskLevel.toUpperCase()}

### Affected Files

${affectedList}

---

## Acceptance Criteria

${criteriaList}

---

## Verification Commands

RepoMind will run the following commands after Bob's implementation.
All commands must exit with code 0 for the verification to pass.

${commandList}

---

*Generated by RepoMind — do not edit manually.*
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface WriteTaskResult {
  taskSpec: TaskSpec;
  taskMdPath: string;
  taskJsonPath: string;
  commitSha: string;
}

/**
 * Build a TaskSpec from the impact report, write TASK.md and task.json into
 * the demo repository, and commit both files.
 *
 * @param repoPath      Absolute path to the demo repository (task-api).
 * @param changeRequest The developer's original change request string.
 * @param impact        The ImpactReport produced by lib/impactAnalyser.
 */
export function writeTask(
  repoPath: string,
  changeRequest: string,
  impact: ImpactReport,
): WriteTaskResult {
  // Build the acceptance criteria from the test scope — these are the concrete
  // checks Bob must not break
  const acceptanceCriteria: string[] = [
    ...impact.testScope,
    `npm run build must exit 0`,
    `npm test must exit 0`,
  ];

  const taskSpec: TaskSpec = {
    version: '1',
    changeRequest,
    affectedFiles: impact.affectedFiles,
    riskLevel: impact.riskLevel,
    acceptanceCriteria,
    verificationCommands: ['npm run build', 'npm test'],
  };

  // Write TASK.md
  const taskMdPath = join(repoPath, 'TASK.md');
  writeFileSync(taskMdPath, renderTaskMd(taskSpec), 'utf8');

  // Write task.json
  const taskJsonPath = join(repoPath, 'task.json');
  writeFileSync(taskJsonPath, JSON.stringify(taskSpec, null, 2), 'utf8');

  // Commit both files to the demo repo so Bob starts from a clean state
  const commitSha = commitFiles(
    repoPath,
    ['TASK.md', 'task.json'],
    `chore(repomind): write task — ${changeRequest.slice(0, 72)}`,
  );

  return {
    taskSpec,
    taskMdPath,
    taskJsonPath,
    commitSha,
  };
}
